### ISSUE TITLE
Cadastrar Unidades de Medida

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#11]
Henrique, conversei com o cliente e a gente identificou as seguintes unidades de medida possíveis:
- un
- g
- kg
- ml
- l
- porção

Note que a porção não quer dizer nada. Mas a gente tem que informar ao usuário que isso existe e ele precisa comprar caso não tenha em casa (ex. manjericão). Se ele vai comprar 1kg ou um ramo, problema dele...

**Comment by henriquemattos** [comment]
As duas medidas foram inseridas mas não foi removida a opção "mg" que já constava, embora não esteja na lista acima. Para atualizar as medidas, além de atualizar o plugin, é necessário desativá-lo e ativá0lo novamente.

**Comment by EdRolla** [comment]
ok
