### ISSUE TITLE
Passar unidade de medida para a tela Cadastro de Ingrediente

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#12]
Após alinhamento com o cliente, concluímos que é melhor instanciar a unidade de medida no cadastramento do ingrediente (/wp-admin/edit-tags.php?taxonomy=freez_ingredients&post_type=freez_recipes)  e não na tela de Nova Receita (/wp-admin/post-new.php?post_type=freez_recipes). 

Sendo assim, para cadastrar um ingrediente, precisaremos dos seguintes campos:
- Nome - string já existente;
- Slug - url já existente;
- Unidade de Medida - dropdown com os valores [un., g, kg, l, ml, porção]; e
- Descrição - texto já existente (não sei se precisa, mas não machuca de estar lá).

Quando estiver cadastrando uma Receita, a unidade de medida (atualmente um dropdown) será apenas um label (readonly).

**Comment by henriquemattos** [comment]
Conforme conversado pelo skype, foi concordado em deixar a instância de unidade no cadastro de receita.
