### ISSUE TITLE
Trocar elemento H3 por p

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#13]
Mestre, o shortcode retorna um trecho de código com um elemento h3, como abaixo:
```<div class="recipes-list">
<article id="recipes-1352" class="recipes-1352 post type-recipe">
<h3><input type="checkbox" name="checkbox-recipes-1352">Macarrão à Bolonhesa</h3>
</article>
<article id="recipes-1353" class="recipes-1353 post type-recipe">
<h3><input type="checkbox" name="checkbox-recipes-1353">Macarrão ao Molho Branco</h3>
</article>
<div><button type="button">Imprimir lista de compras</button></div>
</div>
```

Seria possível trocar este h3 por um parágrafo? 
Seria um baita adianto aqui! ;)

**Comment by henriquemattos** [comment]
Alterei e subi já pro repositório mas na versão da correção foi junto a versão do PDF que ainda não está 100%. Ele gera o PDF corretamente mas o layout do PDF ainda está meio zoado.
