### ISSUE TITLE
Parâmetro link com valor false como default

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#16]
Por gentileza, Henrique, deixe o parâmetro "link" do shortcode como "false" por default.

**Comment by henriquemattos** [comment]
Como era: se o usuário não passar o parâmetro, ele entendia como diferente de falso, então gerava o atributo (links e checkboxes).

Como ficou: se o usuário não passar o parâmetro ou passar (link="false"|checkbox="false"), não gera o atributo. Se passar (link="true"|checkbox="true"), aparecem os atributos.
