### ISSUE TITLE
Ver Lista sem alerta de popup

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#20]
procurar outra abordagem que não necessite permissão de popup para abir a lista. 
Não tem problema de ser na mesma aba.

**Comment by henriquemattos** [comment]
Foi criado um método para gerar um alerta no usuário para ele saber que o navegador bloqueou a nova janela com a lista de receitas. Essa é uma função nativa dos navegadores e não tem como "burlar". Uma alternativa seria construir a visualização dentro do HTML do template, mas isso pode implicar em grandes conflitos de JS e CSS entre o plugin, o Tema e o WP.
