### ISSUE TITLE
Revisão de Layout

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#26]
* Diminuir altura da linha dos li's - Se possível, diminuir o lineheight dos elementos para não ficarem tão distantes as linhas umas das outras. Isso ocasiona quebra de linha prematuramente e ele está preocupado com a percepção do cliente final. 
Se não conseguir, pode diminuir o tamanho da fonte dos números. 

* Redução de tamanho de fonte de texto simples (li)- requisitou um tamanho de fonte de 15px, pois a outra estava muito grande.

**Comment by henriquemattos** [comment]
- [ ] Diminuir altura da linha na lista de dicas;
- [ ] Reduzir fonte dos textos na lista de dicas;
