### ISSUE TITLE
Perda de Dados

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#27]
Cuidado com perda de dados ao dar update no plugin.

Quando habilitei o último release, as unidades de medida foram para o espaço e o cliente me xingou de tudo quanto era nome. (xingou mesmo kkkkkkkk)

Imagino que as tabelas não existiam e tals, e por isso rolou essa aparente perda. Mas, se for acontecer isso, preciso estar ciente para avisar ele antes de dar a zica, ok?

**Comment by henriquemattos** [comment]
Não houve perda de dados. As medidas estavam gravadas no arquivo de configuração do plugin. Ao criar uma área de gerenciamento de medidas, eu retirei do arquivo de gerenciamento. Se ele cadastrar as medidas como estavam antes (mg, g, kg, ml, l, un, etc...) voltam todos aos normais. Os ingredientes ficam salvos "agnósticos" à tabela de ingredientes e de medidas. Se precisar alterar um ingrediente no gerenciamento de ingredientes, por exemplo, é preciso alterá-lo em cada produto. Não há relacionamento de tabelas para isso.
