### ISSUE TITLE
Inserir exclusiva de Ingredientes

### ISSUE THREAD

**Issue by henriquemattos** [henriquemattos/freez-recipes#3]
Ingredientes da receita deverão ser previamente cadastrados na área específica para aparecerem na lista de ingredientes no cadastro/edição de receitas.

**Comment by EdRolla** [comment]
Só para certificar, ideal é que (no menu lateral) haja um link "Novo Ingrediente", ficando o menu com a seguinte estrutura:
Receitas > 
- Todas as Receitas (atualmente está como "Receitas")
- Nova Receita (atualmente está como "Adicionar Novo")
- Todos os Ingrediente
- Novo Ingrediente
- Categorias

No cadastro de ingredientes, bastariam os campos: nome e unidade de medida (kg, g, pacote, ramo, ml, l, etc.). 
Na tela de cadastro de receita, a gente teria os campos:
- Ingrediente - que pode ser um dropdown (mas eu preferiria um texto com autocomplete);
- Quantidade - um número; e
- Unidade de Medida - um readonly que puxa a unidade de medida do ingrediente previamente cadastrado.
