### ISSUE TITLE
Exemplo para conversão de unidade de medida dos ingredientes

### ISSUE THREAD

**Issue by henriquemattos** [henriquemattos/freez-recipes#6]
Usar a tabela de medidas do Receitas IG: http://receitas.ig.com.br/guia-do-cozinheiro/medidas/

**Comment by EdRolla** [comment]
Acho que pode ser esforço desnecessário.
Eu sugiro não implementar a funcionalidade, deixar a necessidade surgir naturalmente e entregar em um update futuro (e, claro, cobrar para isso). ;)

**Comment by henriquemattos** [comment]
Fechada por não ser necessário neste momento.

**Comment by EdRolla** [comment]
Dei com a língua nos dentes. 
Como você previu, quando mostrei o plugin para ele, foi uma das primeiras coisas que ele deu falta. (fico me perguntando porque cliente não menciona isso no briefing?!?!)

Peço gentilmente que reabra o issue, pois precisaremos tratá-lo. As receitas conterão medidas <em>não convencionais</em> (como colher de chá, ramos, pitadas) e a lista de compra precisará estar em medidas convencionais.

**Comment by EdRolla** [comment]
Conversei mais com o cliente e a conversão não será mais necessária. 
A responsabilidade de converter será do chef que está cadastrando a receita. Na descrição da receita, ele informará ao usuário em medidas não convencionais (colher, xícara, etc) e, nos ingredientes, informará a medida formal (unidade, g, ml, etc)
