### ISSUE TITLE
Ingredientes Vazios

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#8]
Ao cadastrar uma nova receita, se clicar uma vez a mais no botão "Novo Ingrediente" e salvar, a receita passa a ter aquele campo vazio. 

Acho que um botãozinho "**X**" vermelho ao lado direito de cada ingrediente para remover, resolve esse problema.

**Comment by henriquemattos** [comment]
Esse bug foi corrigido antes de ter uma issue aberta. Basta baixar o zip aqui do Github, descompactar e sobrescrever na pasta wp-content/plugins. Acredito que baixando o zip possa ser feito o upload pela página de plugins -> adicionar novo do Admin no WP.
