### ISSUE TITLE
Lembrete do Shortcode

### ISSUE THREAD

**Issue by EdRolla** [henriquemattos/freez-recipes#9]
Na tela "Todas as Receitas" (bem como na edição da receita) acho que deveria ter um lembrete com o shortcode para facilitar a vida do operador. 

Um bom exemplo disso pode ser tirado do plugin Contact Form 7.

**Comment by henriquemattos** [comment]
Excelente ideia. O shortcode agora é exibido na página de criação, edição e lista de receitas. :)
